# Generated by Django 3.2.8 on 2021-10-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=10485760)),
            ],
            options={
                'db_table': 'Authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookpoint',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10485760)),
                ('adress', models.CharField(max_length=10485760)),
                ('eisk', models.FloatField()),
            ],
            options={
                'db_table': 'BookPoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10485760)),
                ('place', models.CharField(max_length=10485760)),
                ('publ', models.CharField(max_length=10485760)),
                ('year', models.CharField(max_length=4)),
                ('lan', models.CharField(max_length=3)),
                ('rubrics', models.CharField(max_length=10485760)),
                ('person', models.CharField(max_length=10485760)),
                ('serial', models.CharField(max_length=10485760)),
                ('material', models.CharField(max_length=10485760)),
                ('biblevel', models.CharField(max_length=10485760)),
                ('ager', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'Catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('cirid', models.IntegerField(db_column='cirID', primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=10485760)),
                ('startdate', models.DateField(db_column='startDate')),
                ('finishdate', models.DateField(db_column='finishDate')),
                ('state', models.CharField(max_length=10485760)),
            ],
            options={
                'db_table': 'Circulation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('inventorynumber', models.IntegerField(db_column='inventoryNumber')),
                ('barcode', models.CharField(db_column='barCode', max_length=10485760)),
                ('trackindex', models.CharField(db_column='trackIndex', max_length=10485760)),
            ],
            options={
                'db_table': 'Fond',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('abisid', models.IntegerField(db_column='abisID', primary_key=True, serialize=False)),
                ('dateofbirth', models.DateField(db_column='dateOfBirth')),
                ('adress', models.CharField(max_length=10485760)),
            ],
            options={
                'db_table': 'Readers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10485760)),
            ],
            options={
                'db_table': 'Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Siglas',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10485760)),
                ('adress', models.CharField(max_length=10485760)),
                ('eisk', models.FloatField()),
            ],
            options={
                'db_table': 'Siglas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Siglasnic',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Siglasnic',
                'managed': False,
            },
        ),
    ]
